# Uncomment this line to define a global platform for your project platform :ios, '8.0'

target 'YangFenPlatform' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YangFenPlatform
  pod 'GDataXML-HTML', '~> 1.3.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry', '~> 0.6.4'
  pod 'SVProgressHUD', '~> 2.1.2'
end
